/* ═══════════════════════════════════════════════════════════
   نظام جرد المختبر — data.js
   البيانات الأساسية: الموظفون + الأجهزة + المحاليل
   ═══════════════════════════════════════════════════════════ */

/* ─── قائمة الموظفين (19 موظف) ─── */
var EMPLOYEES_LIST = [
  "سعد علي سعد القرني",
  "مسفر عائض محمد القرني",
  "محمد دخيل الله محمد الغامدي",
  "محمد خلف أحمد الخثعمي",
  "محمد سهلان سعد العليياني",
  "فهد عبد الله محمد القرني",
  "سلطان محمد دخيل القرني",
  "محمد سعد عبد الله القرني",
  "نايف عبد الله محبوب القرني",
  "حاتم خليفة كرار",
  "سعد عيد سعيد آل سعد القرني",
  "حسام سعيد عبد الله القرني",
  "محمد ناصر محمد القرني",
  "عبدالرحمن صالح عبدالرحمن القرني",
  "بدر محمد ماكن القرني",
  "عبدالعزيز راشد جديع البريدي",
  "منصور محمد منصور القرني",
  "نايف محمد عبد الله العليياني",
  "محمد صالح محمد الخثعمي"
];

/* ─── أنواع المحاليل ─── */
var SUPPLY_TYPES = {
  reagents:    { label: "كاشفات",        icon: "🧪", color: "#1565c0" },
  calibrators: { label: "معايرات",        icon: "⚖️", color: "#6a1b9a" },
  qc:          { label: "ضبط الجودة",     icon: "🔬", color: "#00897b" },
  solutions:   { label: "محاليل التشغيل", icon: "💧", color: "#0277bd" },
  parts:       { label: "قطع وإلكترودات", icon: "⚙️", color: "#5d4037" }
};

/* ─── بيانات الأجهزة ─── */
var SUPPLY_DATA = {

  /* ═══════════════════════════════════════════════════════════
     جهاز Siemens Atellica
     ═══════════════════════════════════════════════════════════ */
  "siemens_atellica": {
    id: "siemens_atellica",
    name: "Siemens Atellica",
    short: "Atellica",
    company: "Siemens",
    icon: "🔬",
    supplies: [
      /* ── كاشفات (CH) ── */
      { id: 1,  name: "Ammonia (AMM)",            type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 2,  name: "Albumin (ALB)",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 3,  name: "Calcium (CA)",             type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 4,  name: "Cholesterol (CHOL_2)",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 5,  name: "Creatinine (CREA_2)",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 6,  name: "Glucose (GluH_3)",         type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 7,  name: "Iron (Iron_2)",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 8,  name: "Magnesium (Mg)",           type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 9,  name: "Inorganic Phosphate (IP)", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 10, name: "Total Protein (TP_2)",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 11, name: "Triglycerides (Trig_2)",   type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 12, name: "Uric Acid (UA)",           type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 13, name: "Urea Nitrogen (UN_c)",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 14, name: "Direct Bilirubin (DBil)",  type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 15, name: "Total Bilirubin (TBil)",   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 16, name: "Amylase (AMY_2)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 17, name: "Lactate (Lac_3)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 18, name: "TIBC",                     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 19, name: "ALP_2",                    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 20, name: "GGT_2",                    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 21, name: "LDH",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 22, name: "Lipase (LIP)",             type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 23, name: "ALT",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 24, name: "AST",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 25, name: "CK_L",                     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 26, name: "HDL Cholesterol",          type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 27, name: "LDL Cholesterol",          type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 28, name: "Electrolytes (Na,K,Cl)",   type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 29, name: "HbA1c (A1C_E)",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 30, name: "CRP (RCRP)",               type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 31, name: "Microalbumin (uALB)",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 32, name: "Urine Protein (UCFP)",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },

      /* ── كاشفات (IM) ── */
      { id: 33, name: "TSH3UL",                   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 34, name: "FT3",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 35, name: "FT4",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 36, name: "LH",                       type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 37, name: "FSH",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 38, name: "Prolactin (PRL)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 39, name: "THCG",                     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 40, name: "Vitamin B12 (VB12)",       type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 41, name: "Ferritin (FER)",           type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 42, name: "AFP",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 43, name: "CEA",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 44, name: "Progesterone (PRGE)",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 45, name: "Cortisol (CORP)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 46, name: "PSA",                      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 47, name: "Free PSA (fPSA)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 48, name: "Estradiol (E2)",           type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 49, name: "Folate (Fol)",             type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 50, name: "Testosterone (TSTII)",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 51, name: "PTH",                      type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 52, name: "Vitamin D (VITD)",         type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 53, name: "CK-MB",                    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 54, name: "NT-proBNP (PBNP)",         type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 55, name: "Troponin I (TNI)",         type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 56, name: "Anti-Tg II (aTgII)",       type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 57, name: "Procalcitonin (PCT)",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 58, name: "HBsII",                    type: "reagents", qty: 0, minQty: 3, kitDays: 21 },
      { id: 59, name: "aHCV",                     type: "reagents", qty: 0, minQty: 3, kitDays: 21 },
      { id: 60, name: "CHIV",                     type: "reagents", qty: 0, minQty: 3, kitDays: 21 },
      { id: 61, name: "SYPH",                     type: "reagents", qty: 0, minQty: 3, kitDays: 21 },
      { id: 62, name: "aHBs2",                    type: "reagents", qty: 0, minQty: 3, kitDays: 21 },
      { id: 63, name: "C-peptide (Cps)",          type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 64, name: "Insulin (IRI)",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 65, name: "CA19-9",                   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 66, name: "CA15-3",                   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 67, name: "CA125",                    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 68, name: "Her-2/neu (H2n)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },

      /* ── معايرات CH ── */
      { id: 69, name: "CHEM CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 70, name: "BILI CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 71, name: "SPCL CHEM CAL",            type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 72, name: "ENZ 1 CAL",                type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 73, name: "ENZ 2 CAL",                type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 74, name: "ENZ 3 CAL",                type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 75, name: "CHDLC CAL",                type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 76, name: "LDLC CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 77, name: "A1C_E CAL",                type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 78, name: "RCRP CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 79, name: "uALB CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },
      { id: 80, name: "UCFP CAL",                 type: "calibrators", qty: 0, minQty: 5, kitDays: 60 },

      /* ── معايرات IM ── */
      { id: 81,  name: "TSH CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 82,  name: "FT3 CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 83,  name: "FT4 CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 84,  name: "LH CAL",                  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 85,  name: "FSH CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 86,  name: "PRL CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 87,  name: "THCG CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 88,  name: "VB12 CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 89,  name: "FER CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 90,  name: "AFP CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 91,  name: "CEA CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 92,  name: "PRGE CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 93,  name: "CORP CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 94,  name: "PSA CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 95,  name: "fPSA CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 96,  name: "E2 CAL",                  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 97,  name: "FOL CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 98,  name: "TSTII CAL",               type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 99,  name: "PTH CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 100, name: "VITD CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 101, name: "CKMB CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 102, name: "PBNP CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 103, name: "TNI CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 104, name: "aTgII CAL",               type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 105, name: "PCT CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 106, name: "HBsII CAL",               type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 107, name: "aHCV CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 108, name: "CHIV CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 109, name: "SYPH CAL",                type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 110, name: "aHBs2 CAL",               type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 111, name: "Cps CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 112, name: "IRI CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 113, name: "CA19-9 CAL",              type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 114, name: "CA15-3 CAL",              type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 115, name: "CA125 CAL",               type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 116, name: "H2n CAL",                 type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 117, name: "Multi-Dil 1",             type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 118, name: "Multi-Dil 2",             type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 119, name: "Multi-Dil 3",             type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 120, name: "Multi-Dil 10",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 121, name: "Multi-Dil 11",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 122, name: "Multi-Dil 13",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 123, name: "Multi-Dil 15",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      /* ── QC ── */
      { id: 124, name: "CHEM CAL QC",             type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 125, name: "CH QC",                   type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 126, name: "A1c QC",                  type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 127, name: "RCRP QC",                 type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 128, name: "Specific Protein QC",     type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 129, name: "Urine QC",                type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 130, name: "PTH QC",                  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 131, name: "VITD QC",                 type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 132, name: "PCT QC",                  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 133, name: "CRD QC",                  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 134, name: "HBsII QC",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 135, name: "aHCV QC",                 type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 136, name: "CHIV QC",                 type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 137, name: "SYPH QC",                 type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 138, name: "aHBs2 QC",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 139, name: "ATGII QC",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 140, name: "IA Premium 1",            type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 141, name: "IA Premium 3",            type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 142, name: "TMR QC",                  type: "qc", qty: 0, minQty: 2, kitDays: 30 },

      /* ── محاليل التشغيل ── */
      { id: 143, name: "APW1",                    type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 144, name: "APW3",                    type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 145, name: "PW3",                     type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 146, name: "VB12 Dil",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 147, name: "VB12 DTT/REL",            type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 148, name: "T3/T4/VB12 ANC",          type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 149, name: "THCG Dil",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 150, name: "CEA Dil",                 type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 151, name: "E2 Dil",                  type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 152, name: "FPSA CAL/Dil",            type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 153, name: "Fol DTT/REL",             type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 154, name: "Fol DIL",                 type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 155, name: "Folserum",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 156, name: "RBC Fol",                 type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 157, name: "19-9 DIL",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 158, name: "VITD Dil",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 159, name: "CKMB Dil",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 160, name: "IRI DILI",                type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 161, name: "Standard A",              type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 162, name: "Standard B",              type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 163, name: "Standard F",              type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 164, name: "Salt",                    type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 165, name: "Diluent",                 type: "solutions", qty: 0, minQty: 2, kitDays: 30 },

      /* ── قطع ── */
      { id: 166, name: "Tips",                    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 167, name: "Cups",                    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 168, name: "Cell Wash Reaction",      type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 169, name: "Lamp",                    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 170, name: "Sensor",                  type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Cobas Pure (C303 + e402)
     ═══════════════════════════════════════════════════════════ */
  "cobas_pure": {
    id: "cobas_pure",
    name: "Cobas Pure (C303 + e402)",
    short: "Pure",
    company: "Roche",
    icon: "🧬",
    supplies: [
      /* C303 كاشفات */
      { id: 1,  name: "GLU",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 2,  name: "UREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 3,  name: "CREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 4,  name: "UA",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 5,  name: "TP",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 6,  name: "ALB",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 7,  name: "ALT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 8,  name: "AST",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 9,  name: "TBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 10, name: "DBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 11, name: "GGT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 12, name: "ALP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 13, name: "LIP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 14, name: "AMY",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 15, name: "LDH",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 16, name: "CK",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 17, name: "CK-MB",   type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 18, name: "CHOL",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 19, name: "TG",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 20, name: "HDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 21, name: "LDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 22, name: "Ca",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 23, name: "PHOS",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 24, name: "Mg",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 25, name: "Fe-Iron", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 26, name: "UIBC",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 27, name: "NH3",     type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 28, name: "CRP",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 29, name: "HbA1c",   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 30, name: "ALBU2",   type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 31, name: "TPU3",    type: "reagents", qty: 0, minQty: 5, kitDays: 30 },

      /* e402 كاشفات */
      { id: 32, name: "TSH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 33, name: "FT4",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 34, name: "FT3",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 35, name: "HCG-Beta",             type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 36, name: "Prolactin",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 37, name: "LH",                   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 38, name: "FSH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 39, name: "Testosterone (Total)", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 40, name: "Estradiol (E2)",       type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 41, name: "Progesterone",         type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 42, name: "Cortisol (AM)",        type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 43, name: "DHEA-S",               type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 44, name: "PTH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 45, name: "Insulin (Fasting)",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 46, name: "C-peptide",            type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 47, name: "PSA (Total)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 48, name: "Vitamin B12",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 49, name: "Vitamin D Total",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 50, name: "Folate",               type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 51, name: "Ferritin",             type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 52, name: "AFP",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 53, name: "CA-125",               type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 54, name: "CA 15-3",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 55, name: "CA 19-9",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 56, name: "CA 72-3",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 57, name: "CEA",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 58, name: "TnI",                  type: "reagents", qty: 0, minQty: 5, kitDays: 14 },

      /* C303 معايرات */
      { id: 59, name: "CFAS",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 60, name: "MB Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 61, name: "Protein Cal",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 62, name: "Fe Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 63, name: "Lipid Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 64, name: "A1c Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 65, name: "PUC Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 66, name: "AMM Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 67, name: "ISE Low Cal",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 68, name: "ISE High Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 69, name: "Fe Standard",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      /* e402 معايرات */
      { id: 70, name: "TSH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 71, name: "FT4 Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 72, name: "FT3 Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 73, name: "HCG Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 74, name: "Prolactin Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 75, name: "LH Cal",           type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 76, name: "FSH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 77, name: "Testosterone Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 78, name: "E2 Cal",           type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 79, name: "Progesterone Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 80, name: "Cortisol Cal",     type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 81, name: "DHEA-S Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 82, name: "PTH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 83, name: "Insulin Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 84, name: "C-peptide Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 85, name: "PSA Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 86, name: "VB12 Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 87, name: "VitD Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 88, name: "Folate Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 89, name: "Ferritin Cal",     type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 90, name: "AFP Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 91, name: "Tumor Marker Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 92, name: "CEA Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 93, name: "TnI Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      /* QC */
      { id: 94, name: "PreciControl TM L1",  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 95, name: "PreciControl MM",     type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 96, name: "PreciControl Vit-D",  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 97, name: "PCC1",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 98, name: "PCC2",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 99, name: "Control V",           type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 100, name: "Control U",          type: "qc", qty: 0, minQty: 2, kitDays: 30 },

      /* محاليل تشغيل */
      { id: 101, name: "ProCell 2M",         type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 102, name: "PreClean 2M",        type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 103, name: "CleanCell M",        type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 104, name: "ISE Inter Standard", type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 105, name: "ISE Diluent G2",     type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 106, name: "ISE REF Electrolyte",type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 107, name: "Basic Wash",         type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 108, name: "Acid Wash",          type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 109, name: "ECO-D",              type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 110, name: "NAOHD",              type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 111, name: "SMS",                type: "solutions", qty: 0, minQty: 3, kitDays: 30 },

      /* قطع */
      { id: 112, name: "Na Electrode",       type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 113, name: "K Electrode",        type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 114, name: "Cl Electrode",       type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 115, name: "REF Electrode",      type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 116, name: "Tips",               type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 117, name: "Cups",               type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 118, name: "Reaction Cell C303", type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 119, name: "Lamp",               type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Cobas c311
     ═══════════════════════════════════════════════════════════ */
  "cobas_c311": {
    id: "cobas_c311",
    name: "Cobas c311",
    short: "c311",
    company: "Roche",
    icon: "🧪",
    supplies: [
      { id: 1,  name: "GLU",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 2,  name: "HbA1c",   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 3,  name: "UREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 4,  name: "CREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 5,  name: "UA",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 6,  name: "TP",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 7,  name: "ALB",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 8,  name: "ALT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 9,  name: "AST",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 10, name: "TBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 11, name: "DBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 12, name: "LIP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 13, name: "AMY",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 14, name: "GGT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 15, name: "ALP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 16, name: "CHOL",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 17, name: "TG",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 18, name: "HDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 19, name: "LDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 20, name: "CK",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 21, name: "CK-MB",   type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 22, name: "LDH",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 23, name: "Ca",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 24, name: "PHOS",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 25, name: "Mg",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 26, name: "Fe-Iron", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 27, name: "UIBC",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 28, name: "NH3",     type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 29, name: "CRP",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 30, name: "ALBU2",   type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 31, name: "TPU3",    type: "reagents", qty: 0, minQty: 5, kitDays: 30 },

      { id: 32, name: "CFAS",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 33, name: "MB Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 34, name: "Protein Cal",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 35, name: "Fe Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 36, name: "Lipid Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 37, name: "A1c Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 38, name: "PUC Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 39, name: "AMM Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 40, name: "ISE Low Cal",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 41, name: "ISE High Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 42, name: "Fe Standard",  type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      { id: 43, name: "PreciControl TM L1",  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 44, name: "PreciControl MM",     type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 45, name: "PreciControl Vit-D",  type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 46, name: "PCC1",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 47, name: "PCC2",                type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 48, name: "Control V",           type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 49, name: "Control U",           type: "qc", qty: 0, minQty: 2, kitDays: 30 },

      { id: 50, name: "ISE Inter Standard",                 type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 51, name: "ISE Diluent G2",                     type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 52, name: "ISE REF Electrolyte",                type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 53, name: "Cell Wash Solution 1 / NAOHD",       type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 54, name: "Cell Wash Solution 2 / Acid Wash",   type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 55, name: "Sample Cleaner 1",                   type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 56, name: "Sample Cleaner 2",                   type: "solutions", qty: 0, minQty: 3, kitDays: 30 },

      { id: 57, name: "Na Electrode",        type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 58, name: "K Electrode",         type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 59, name: "Cl Electrode",        type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 60, name: "REF Electrode",       type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 61, name: "Reaction Cell c311",  type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 62, name: "Halogen Lamp c311",   type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 63, name: "Tips",                type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 64, name: "Cups",                type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Cobas e411
     ═══════════════════════════════════════════════════════════ */
  "cobas_e411": {
    id: "cobas_e411",
    name: "Cobas e411",
    short: "e411",
    company: "Roche",
    icon: "⚗️",
    supplies: [
      { id: 1,  name: "TSH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 2,  name: "FT4",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 3,  name: "FT3",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 4,  name: "HCG-Beta",             type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 5,  name: "Prolactin",            type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 6,  name: "LH",                   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 7,  name: "FSH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 8,  name: "Testosterone (Total)", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 9,  name: "Estradiol (E2)",       type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 10, name: "Progesterone",         type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 11, name: "Cortisol (AM)",        type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 12, name: "DHEA-S",               type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 13, name: "PTH",                  type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 14, name: "Insulin (Fasting)",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 15, name: "C-peptide",            type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 16, name: "PSA (Total)",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 17, name: "Vitamin B12",          type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 18, name: "Vitamin D Total",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 19, name: "Folate",               type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 20, name: "Ferritin",             type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 21, name: "AFP",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 22, name: "CA-125",               type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 23, name: "CA 15-3",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 24, name: "CA 19-9",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 25, name: "CA 72-3",              type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 26, name: "CEA",                  type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 27, name: "TnI",                  type: "reagents", qty: 0, minQty: 5, kitDays: 14 },

      { id: 28, name: "TSH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 29, name: "FT4 Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 30, name: "FT3 Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 31, name: "HCG Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 32, name: "Prolactin Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 33, name: "LH Cal",           type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 34, name: "FSH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 35, name: "Testosterone Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 36, name: "E2 Cal",           type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 37, name: "Progesterone Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 38, name: "Cortisol Cal",     type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 39, name: "DHEA-S Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 40, name: "PTH Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 41, name: "Insulin Cal",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 42, name: "C-peptide Cal",    type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 43, name: "PSA Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 44, name: "VB12 Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 45, name: "VitD Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 46, name: "Folate Cal",       type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 47, name: "Ferritin Cal",     type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 48, name: "AFP Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 49, name: "Tumor Marker Cal", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 50, name: "CEA Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 51, name: "TnI Cal",          type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      { id: 52, name: "PreciControl TM L1", type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 53, name: "PreciControl MM",    type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 54, name: "PreciControl Vit-D", type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 55, name: "Control V",          type: "qc", qty: 0, minQty: 2, kitDays: 30 },
      { id: 56, name: "Control U",          type: "qc", qty: 0, minQty: 2, kitDays: 30 },

      { id: 57, name: "ProCell",   type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 58, name: "CleanCell", type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 59, name: "PreClean",  type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 60, name: "SysClean",  type: "solutions", qty: 0, minQty: 3, kitDays: 30 },

      { id: 61, name: "Tips",    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 62, name: "Cups",    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 63, name: "Probe",   type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 64, name: "Syringe", type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Dimension EXL 200
     ═══════════════════════════════════════════════════════════ */
  "dimension_exl200": {
    id: "dimension_exl200",
    name: "Dimension EXL 200",
    short: "EXL200",
    company: "Siemens",
    icon: "🔭",
    supplies: [
      { id: 1,  name: "GLU",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 2,  name: "HbA1c",   type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 3,  name: "UREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 4,  name: "CREA",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 5,  name: "UA",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 6,  name: "TP",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 7,  name: "ALB",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 8,  name: "ALT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 9,  name: "AST",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 10, name: "TBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 11, name: "DBIL",    type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 12, name: "AMY",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 13, name: "LIP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 14, name: "GGT",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 15, name: "ALP",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 16, name: "CHOL",    type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 17, name: "TG",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 18, name: "HDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 19, name: "LDL",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 20, name: "CK",      type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 21, name: "CK-MB",   type: "reagents", qty: 0, minQty: 5, kitDays: 14 },
      { id: 22, name: "LDH",     type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 23, name: "Ca",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 24, name: "PHOS",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 25, name: "Mg",      type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 26, name: "Fe-Iron", type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 27, name: "IBCT",    type: "reagents", qty: 0, minQty: 5, kitDays: 21 },
      { id: 28, name: "NH3",     type: "reagents", qty: 0, minQty: 5, kitDays: 30 },
      { id: 29, name: "CRP",     type: "reagents", qty: 0, minQty: 5, kitDays: 14 },

      { id: 30, name: "Enz Cal CK-MB",      type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 31, name: "Multi Calibrator 2", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 32, name: "ALP Cal",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 33, name: "ALT Calibrator",     type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 34, name: "TP/ALB Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 35, name: "Bil T/D Cal",        type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 36, name: "Chem 1 Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 37, name: "Iron Cal",           type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 38, name: "AMM Cal",            type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 39, name: "Lipase Cal",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 40, name: "Verify Enz",         type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },
      { id: 41, name: "Chek Lyte Solution", type: "calibrators", qty: 0, minQty: 3, kitDays: 60 },

      { id: 42, name: "QC Level 2 & 3", type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 43, name: "A1c Control",    type: "qc", qty: 0, minQty: 3, kitDays: 30 },
      { id: 44, name: "CRP Control",    type: "qc", qty: 0, minQty: 3, kitDays: 14 },

      { id: 45, name: "Standard A", type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 46, name: "Standard B", type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 47, name: "Standard F", type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 48, name: "Salt",       type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 49, name: "Diluent",    type: "solutions", qty: 0, minQty: 3, kitDays: 30 },
      { id: 50, name: "CHE",        type: "solutions", qty: 0, minQty: 3, kitDays: 21 },

      { id: 51, name: "Sensor",  type: "parts", qty: 0, minQty: 1, kitDays: 30 },
      { id: 52, name: "Probe",   type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 53, name: "Cuvette", type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Mini VIDAS
     ═══════════════════════════════════════════════════════════ */
  "mini_vidas": {
    id: "mini_vidas",
    name: "Mini VIDAS",
    short: "VIDAS",
    company: "bioMérieux",
    icon: "🩺",
    supplies: [
      { id: 1, name: "Troponin I TestPak", type: "reagents", qty: 0, minQty: 3, kitDays: 14 },
      { id: 2, name: "bHCG Kit",           type: "reagents", qty: 0, minQty: 3, kitDays: 30 },
      { id: 3, name: "Troponin Calibrator",type: "calibrators", qty: 0, minQty: 1, kitDays: 7 },
      { id: 4, name: "bHCG Calibrator S1", type: "calibrators", qty: 0, minQty: 1, kitDays: 7 },
      { id: 5, name: "Cardiac Control",    type: "qc", qty: 0, minQty: 1, kitDays: 30 },
      { id: 6, name: "bHCG Control QC1",   type: "qc", qty: 0, minQty: 1, kitDays: 30 },
      { id: 7, name: "SPR",                type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 8, name: "VIDAS Waste Bag",    type: "parts", qty: 0, minQty: 1, kitDays: 90 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز VARIANT II
     ═══════════════════════════════════════════════════════════ */
  "variant_ii": {
    id: "variant_ii",
    name: "VARIANT II",
    short: "VARIANT",
    company: "Bio-Rad",
    icon: "🩸",
    supplies: [
      { id: 1, name: "HbA1c Kit",             type: "reagents", qty: 0, minQty: 2, kitDays: 21 },
      { id: 2, name: "Calibrator D1 / D2",    type: "calibrators", qty: 0, minQty: 1, kitDays: 60 },
      { id: 3, name: "HbA1c Control L1 / L2", type: "qc", qty: 0, minQty: 1, kitDays: 30 },
      { id: 4, name: "Column / Cartridge",    type: "parts", qty: 0, minQty: 1, kitDays: 90 },
      { id: 5, name: "Buffer A",              type: "solutions", qty: 0, minQty: 2, kitDays: 30 },
      { id: 6, name: "Buffer B",              type: "solutions", qty: 0, minQty: 2, kitDays: 30 }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Alcor iSED
     ═══════════════════════════════════════════════════════════ */
  "alcor_ised": {
    id: "alcor_ised",
    name: "Alcor iSED",
    short: "iSED",
    company: "Alcor Scientific",
    icon: "🩸",
    supplies: [
      { id: 1, name: "Test Card (250 test)",        type: "reagents", qty: 0, minQty: 1, kitDays: 365, note: "REF 112-00250" },
      { id: 2, name: "iWASH Rinse Solution (500mL)", type: "solutions", qty: 0, minQty: 1, kitDays: 30, note: "REF 112-12-001" },
      { id: 3, name: "SEDITROL Quality Control",     type: "qc", qty: 0, minQty: 1, kitDays: 30, note: "REF DSC-01" },
      { id: 4, name: "iWASTE Container (500mL)",     type: "parts", qty: 0, minQty: 1, kitDays: 90, note: "عبوة النفايات" }
    ]
  },

  /* ═══════════════════════════════════════════════════════════
     جهاز Beckman Coulter iChem Velocity
     ═══════════════════════════════════════════════════════════ */
  "beckman_ichem": {
    id: "beckman_ichem",
    name: "Beckman Coulter iChem Velocity",
    short: "iChem",
    company: "Beckman Coulter",
    icon: "🧫",
    supplies: [
      { id: 1, name: "iChem Velocity Urine Chemistry Strips", type: "reagents", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-7204" },
      { id: 2, name: "iQ Lamina",                             type: "reagents", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-3236" },
      { id: 3, name: "iQ Calibrator",                         type: "calibrators", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-3103" },
      { id: 4, name: "iQ Control / Focus Set",                type: "qc", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-3104" },
      { id: 5, name: "Iris Diluent",                          type: "solutions", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-3202" },
      { id: 6, name: "Iris System Cleanser",                  type: "solutions", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-3203" },
      { id: 7, name: "CA/CB/CC Chemistry Controls",           type: "qc", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-7702" },
      { id: 8, name: "CalCheks",                              type: "calibrators", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-7703" },
      { id: 9, name: "iChem Velocity Wash Solution",          type: "solutions", qty: 0, minQty: 1, kitDays: 30, note: "REF 800-7217" }
    ]
  }

};

/* ─── إعدادات ─── */
var APP_CONFIG = {
  storageKey: "lab_inventory_v4",
  warnDaysExpiry: 30,
  warnDaysExpirySoon: 7,
  warnKitDays: 7,
  facilityName: "تجمع عسير الصحي - مستشفى سبت العلايا",
  systemName: "نظام جرد المختبر"
};

/* ─── نهاية data.js ─── */
